// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK2TLu2T_ZAdixJtt1zBIsO53Ew7XTpT4',
    appId: '1:538495280882:web:c5bcfcaa006a754fe6926b',
    messagingSenderId: '538495280882',
    projectId: 'travel-4e259',
    authDomain: 'travel-4e259.firebaseapp.com',
    storageBucket: 'travel-4e259.appspot.com',
    measurementId: 'G-3JKKYCY9T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbogSC6ogaCReLWmBaa962SWZ4eOXntZw',
    appId: '1:538495280882:android:72dc6ddf706dde62e6926b',
    messagingSenderId: '538495280882',
    projectId: 'travel-4e259',
    storageBucket: 'travel-4e259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu66dW8l5O0RL2I12_PS_rsHtRMSbQd4E',
    appId: '1:538495280882:ios:d8f76601478b648ee6926b',
    messagingSenderId: '538495280882',
    projectId: 'travel-4e259',
    storageBucket: 'travel-4e259.appspot.com',
    iosBundleId: 'com.example.travel',
  );
}
